name: Deploy-Overviewer

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  deploy-overviewer:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Deploy Overviewer
        env:
          CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
          CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
          CAPROVER_APP: ${{ secrets.CAPROVER_APPNAME }}
        run: |
          tar -cf ./overviewer.tar Dockerfile captain-definition scheduled_creator.sh
          caprover deploy -t ./overviewer.tar &
          sleep 5

